### ISSUE TITLE
Good practices with commits

### ISSUE THREAD

**Issue by DarckCrystale** [Mannjamin/Ducky-Mc-Duckerson#13]
A commit would be done for a specific thing.
**Example:**
**Bad:** commit when the full application works.
**Good:** commit when a specific part of the application works (like when the bot can say "hello", even if it's not well formatted).

---

A commit message should explain what has been done, not how.
**Example:**
**Bad:** `edited some files`
**Good:** `bot now send Hello message`

---

A commit should reference an issue. This way, in Github 
- when you look at an issue, you can see all the commits pushed to implement it
- when you look at a commit, you can see what issue it references and understand the task that had have to be done

**Example:**
**Bad:** `bot now send Hello message`
**Good:** `Ref #1: bot now send Hello message`
The `#1` is the issue identifier, you can find it at several places (issues list, on the issue itself, on the issue url...). Github will automatically add a link to the issue.

**Comment by AbbyCottontail** [comment]
I'll try, a lot of the time I do big changes in coding for adding a thing, I have been commiting when something works but sometimes it take awhile to get that something.

**Comment by DarckCrystale** [comment]
It's okay, it's an habit to take 🙂
