### ISSUE TITLE
Clean up Readme

### ISSUE THREAD

**Issue by AbbyCottontail** [Mannjamin/Ducky-Mc-Duckerson#16]
An improved readme for Ducky would be lovely.

**Comment by LucileDT** [comment]
What do you want in your README? Did you see that you also have a Wiki in your Github project? (it can be disabled if you don't use it).
![wiki](https://user-images.githubusercontent.com/23707217/29474526-5d215c56-845c-11e7-8335-61f76758ed58.PNG)

**Comment by TouringTroubadour** [comment]
I have cleaned up the Read Me for you Abby, I hope you like it. 

Kind Regards,

Mann
