### ISSUE TITLE
Merge themes into less messages

### ISSUE THREAD

**Issue by AbbyCottontail** [Mannjamin/Ducky-Mc-Duckerson#17]
Discord has a large text limit over IRC, as well as improved text formatting, it also do not have notification as IRC does so currently, as a result of the move over, werewolf sends a lot of text that could be merged into one larger block, possible convert into an embed for better formatting as well.

**Comment by LucileDT** [comment]
Could you add examples for what is done currently and what you would have? 🙂

**Comment by AbbyCottontail** [comment]
I've already made some headway on this, hopefully there's some improvement when I next run and test it.
